name: heidiromano
favicon: null
layout_spectrum: 0.1396758914925158
typography_spectrum: 0.1903025796636939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2512136264704168
  lightness: 0.33014002116397023
  saturation: 0.702916753012687
  rhythmicContrast: 0.3916343841701746
purpose: []
